version: 2
mergeable:
  - when: pull_request.opened, pull_request.edited, pull_request.unlabeled, 
    validate:
      - do: title
        must_exclude:
          regex: ^\[WIP\]
      - do: label
        must_exclude:
          regex: 'wip'
