name: add-to-projects

on:
    issues:
        types:
            - labeled
            - unlabeled

jobs:
  add-to-projects:
    runs-on: ubuntu-latest
    container: quay.io/enarx/fedora-test
    steps:
    - uses: actions/checkout@v2
    
    - name: add-to-project-on-label
      run: cat $GITHUB_EVENT_PATH && python3 .automation/move-to-project.py ${{ secrets.GITHUB_TOKEN }} $GITHUB_REPOSITORY $GITHUB_EVENT_PATH
