name: automation-python

on: [check_run]

jobs:
  automation-python:
    runs-on: ubuntu-latest
    container: quay.io/enarx/fedora-test
    steps:
    - uses: actions/checkout@v2
    
    - name: mirror-issue-metadata-to-pull_request
      run: python3 .automation/automation-python.py ${{ secrets.GITHUB_TOKEN }} $GITHUB_REPOSITORY $GITHUB_EVENT_PATH
