name: label-automation-python

on:
  check_suite:
    types: [completed]

jobs:
  label-automation-python:
    runs-on: ubuntu-latest
    container: quay.io/enarx/fedora-test
    steps:
    - uses: actions/checkout@v2
    
    - name: mirror-issue-labels-to-pull_request
      run: python3 .automation/automation-python.py ${{ secrets.GITHUB_TOKEN }} $GITHUB_REPOSITORY $GITHUB_EVENT_PATH
