name: automation-python

on: [pull_request]

jobs:
  automation-python:
    runs-on: ubuntu-latest
    #container: quay.io/enarx/fedora-test
    steps:
    - uses: actions/checkout@v2
    
    - name: mirror-issue-metadata-to-pull_request
      run: ./.automation/get-pr-number #python3 .automation/automation-python.py {{ secrets.GITHUB_TOKEN }} $GITHUB_REPOSITORY
