name: automation-python-again

on:
  check_suite:
    types: [requested, rerequested, completed]

jobs:
  automation-python-again:
    runs-on: ubuntu-latest
    container: quay.io/enarx/fedora-test
    steps:
    - uses: actions/checkout@v2
    
    - name: mirror-issue-metadata-to-pull_request
      run: cat $GITHUB_EVENT_PATH && python3 .automation/automation-python.py ${{ secrets.GITHUB_TOKEN }} $GITHUB_REPOSITORY $GITHUB_EVENT_PATH
