name: add-to-projects

on:
    issues:
        types:
            - labeled
            - unlabeled

jobs:
  add-to-projects:
    runs-on: ubuntu-latest
    container: quay.io/enarx/fedora
    steps:
    - uses: actions/checkout@v2
    
    - name: scheduled-organization-job
      run: cat $GITHUB_EVENT_PATH && python3 .automation/scheduled-organization-job.py ${{
      secrets.GITHUB_TOKEN }} $GITHUB_REPOSITORY $GITHUB_EVENT_PATH
